### PR TITLE
Fix repo service

### LINKED ISSUE #320: [BUG] Repo service index.json doesn't contains installed/managed files
**Describe the bug**
`ercole repo --rebuild-cache list`  return all artifacts included local installed/managed artifacts present in all directory 

**Expected behavior**
I expected that ercole repo list return all installed artifacts despite the emptiness/unavailability of RepoService.UpstreamRepositories. In the following examples I expected the line
```
i	2019-10-11	???/ercole-agent-win@1.6.1
```

**To Reproduce**
1. cd /tmp
2. git clone https://github.com/ercole-io/ercole.git
3. cd ercole
4. go build -o ercole main.go
5. curl https://pastebin.com/raw/6ePKqn49 | tee override1.toml
6. curl https://pastebin.com/raw/gGzPvxZf | tee override2.toml
7. ./ercole -c override1.toml repo list
8.  ./ercole -c override1.toml repo install ercole-agent/ercole-agent-win@1.6.1
9. ./ercole -c override1.toml repo list
10. rm distributed_files/index.json
11. ./ercole -c override2.toml repo list

**Screenshots, logs, stdout, stderr, asciinema**
https://asciinema.org/a/cEznn2McR7XYQrdVxnuAb4lSE
logs:
```
amreo@amreo-ubuntu-pc:/tmp$ git clone https://github.com/ercole-io/ercole.git
Cloning into 'ercole'...
remote: Enumerating objects: 232, done.
remote: Counting objects: 100% (232/232), done.
remote: Compressing objects: 100% (176/176), done.
remote: Total 7947 (delta 134), reused 110 (delta 52), pack-reused 7715
Ricezione degli oggetti: 100% (7947/7947), 3.01 MiB | 849.00 KiB/s, done.
Risoluzione dei delta: 100% (5603/5603), done.
amreo@amreo-ubuntu-pc:/tmp$ cd ercole
amreo@amreo-ubuntu-pc:/tmp/ercole$ go build -o ercole main.go
amreo@amreo-ubuntu-pc:/tmp/ercole$ curl https://pastebin.com/raw/6ePKqn49 | tee override1.toml
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   229    0   229    0     0    639      0 --:--:-- --:--:-- --:--:--   641
[RepoService]
DistributedFiles = "/tmp/ercole/distributed_files"
  [[RepoService.UpstreamRepositories]]
  Name = "ercole-agent"
  Type = "github-release"
  URL = "https://api.github.com/repos/ercole-io/ercole-agent/releases"amreo@amreo-ubuntu-pc:/tmp/ercole$ curl https://pastebin.com/raw/gGzPvxZf | tee override2.toml
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100    92    0    92    0     0    237      0 --:--:-- --:--:-- --:--:--   237
[RepoService]
DistributedFiles = "/tmp/ercole/distributed_files"
UpstreamRepositories = []amreo@amreo-ubuntu-pc:/tmp/ercole$ ./ercole -c override1.toml repo list
-	2019-08-21	ercole-agent/ercole-agent-rhel6@1.5.0
-	2019-08-21	ercole-agent/ercole-agent-rhel6@1.5.1
-	2019-08-22	ercole-agent/ercole-agent-rhel6@1.5.2
-	2019-08-22	ercole-agent/ercole-agent-rhel6@1.5.3
-	2019-08-23	ercole-agent/ercole-agent-rhel6@1.5.4
-	2019-08-23	ercole-agent/ercole-agent-rhel6@1.5.5
-	2019-08-23	ercole-agent/ercole-agent-rhel6@1.5.6
-	2019-08-30	ercole-agent/ercole-agent-rhel6@1.5.7
-	2019-09-03	ercole-agent/ercole-agent-rhel6@1.5.8
-	2019-09-04	ercole-agent/ercole-agent-rhel6@1.5.10
-	2019-09-06	ercole-agent/ercole-agent-rhel6@1.5.11
-	2019-09-10	ercole-agent/ercole-agent-rhel6@1.5.12
-	2019-10-07	ercole-agent/ercole-agent-rhel6@1.5.13
-	2019-10-07	ercole-agent/ercole-agent-rhel6@1.6.0
-	2019-10-11	ercole-agent/ercole-agent-rhel6@1.6.1
-	2019-10-28	ercole-agent/ercole-agent-rhel6@1.6.2
-	2019-10-31	ercole-agent/ercole-agent-rhel6@1.6.3
-	2019-11-18	ercole-agent/ercole-agent-rhel6@1.6.4
-	2019-12-05	ercole-agent/ercole-agent-rhel6@1.6.5
-	2020-01-14	ercole-agent/ercole-agent-rhel6@1.6.6
-	2020-01-31	ercole-agent/ercole-agent-rhel6@1.6.7
-	2020-02-13	ercole-agent/ercole-agent-rhel6@1.6.8
-	2020-03-19	ercole-agent/ercole-agent-rhel6@1.6.9
-	2020-03-26	ercole-agent/ercole-agent-rhel6@1.6.10
-	2020-03-27	ercole-agent/ercole-agent-rhel6@1.6.11
-	2020-06-08	ercole-agent/ercole-agent-rhel6@1.6.12
-	2019-08-21	ercole-agent/ercole-agent-rhel7@1.5.0
-	2019-08-21	ercole-agent/ercole-agent-rhel7@1.5.1
-	2019-08-22	ercole-agent/ercole-agent-rhel7@1.5.2
-	2019-08-22	ercole-agent/ercole-agent-rhel7@1.5.3
-	2019-08-23	ercole-agent/ercole-agent-rhel7@1.5.4
-	2019-08-23	ercole-agent/ercole-agent-rhel7@1.5.5
-	2019-08-23	ercole-agent/ercole-agent-rhel7@1.5.6
-	2019-08-30	ercole-agent/ercole-agent-rhel7@1.5.7
-	2019-09-03	ercole-agent/ercole-agent-rhel7@1.5.8
-	2019-09-04	ercole-agent/ercole-agent-rhel7@1.5.10
-	2019-09-06	ercole-agent/ercole-agent-rhel7@1.5.11
-	2019-09-10	ercole-agent/ercole-agent-rhel7@1.5.12
-	2019-10-07	ercole-agent/ercole-agent-rhel7@1.5.13
-	2019-10-07	ercole-agent/ercole-agent-rhel7@1.6.0
-	2019-10-11	ercole-agent/ercole-agent-rhel7@1.6.1
-	2019-10-28	ercole-agent/ercole-agent-rhel7@1.6.2
-	2019-10-31	ercole-agent/ercole-agent-rhel7@1.6.3
-	2019-11-18	ercole-agent/ercole-agent-rhel7@1.6.4
-	2019-12-05	ercole-agent/ercole-agent-rhel7@1.6.5
-	2020-01-14	ercole-agent/ercole-agent-rhel7@1.6.6
-	2020-01-31	ercole-agent/ercole-agent-rhel7@1.6.7
-	2020-02-13	ercole-agent/ercole-agent-rhel7@1.6.8
-	2020-03-19	ercole-agent/ercole-agent-rhel7@1.6.9
-	2020-03-26	ercole-agent/ercole-agent-rhel7@1.6.10
-	2020-03-27	ercole-agent/ercole-agent-rhel7@1.6.11
-	2020-06-08	ercole-agent/ercole-agent-rhel7@1.6.12
-	2019-08-21	ercole-agent/ercole-agent-win@1.5.0
-	2019-08-21	ercole-agent/ercole-agent-win@1.5.1
-	2019-08-22	ercole-agent/ercole-agent-win@1.5.2
-	2019-08-22	ercole-agent/ercole-agent-win@1.5.3
-	2019-08-23	ercole-agent/ercole-agent-win@1.5.4
-	2019-08-23	ercole-agent/ercole-agent-win@1.5.5
-	2019-08-23	ercole-agent/ercole-agent-win@1.5.6
-	2019-08-30	ercole-agent/ercole-agent-win@1.5.7
-	2019-09-03	ercole-agent/ercole-agent-win@1.5.8
-	2019-09-04	ercole-agent/ercole-agent-win@1.5.10
-	2019-09-06	ercole-agent/ercole-agent-win@1.5.11
-	2019-09-10	ercole-agent/ercole-agent-win@1.5.12
-	2019-10-07	ercole-agent/ercole-agent-win@1.5.13
-	2019-10-07	ercole-agent/ercole-agent-win@1.6.0
-	2019-10-11	ercole-agent/ercole-agent-win@1.6.1
-	2019-10-28	ercole-agent/ercole-agent-win@1.6.2
-	2019-10-31	ercole-agent/ercole-agent-win@1.6.3
-	2019-11-18	ercole-agent/ercole-agent-win@1.6.4
-	2019-12-05	ercole-agent/ercole-agent-win@1.6.5
-	2020-01-14	ercole-agent/ercole-agent-win@1.6.6
-	2020-01-31	ercole-agent/ercole-agent-win@1.6.7
-	2020-02-13	ercole-agent/ercole-agent-win@1.6.8
-	2020-03-19	ercole-agent/ercole-agent-win@1.6.9
-	2020-03-26	ercole-agent/ercole-agent-win@1.6.10
-	2020-03-27	ercole-agent/ercole-agent-win@1.6.11
-	2020-06-08	ercole-agent/ercole-agent-win@1.6.12
amreo@amreo-ubuntu-pc:/tmp/ercole$ ./ercole -c override1.toml repo install ercole-agent/ercole-agent-win@1.6.1
amreo@amreo-ubuntu-pc:/tmp/ercole$ ./ercole -c override1.toml repo list
-	2019-08-21	ercole-agent/ercole-agent-rhel6@1.5.0
-	2019-08-21	ercole-agent/ercole-agent-rhel6@1.5.1
-	2019-08-22	ercole-agent/ercole-agent-rhel6@1.5.2
-	2019-08-22	ercole-agent/ercole-agent-rhel6@1.5.3
-	2019-08-23	ercole-agent/ercole-agent-rhel6@1.5.4
-	2019-08-23	ercole-agent/ercole-agent-rhel6@1.5.5
-	2019-08-23	ercole-agent/ercole-agent-rhel6@1.5.6
-	2019-08-30	ercole-agent/ercole-agent-rhel6@1.5.7
-	2019-09-03	ercole-agent/ercole-agent-rhel6@1.5.8
-	2019-09-04	ercole-agent/ercole-agent-rhel6@1.5.10
-	2019-09-06	ercole-agent/ercole-agent-rhel6@1.5.11
-	2019-09-10	ercole-agent/ercole-agent-rhel6@1.5.12
-	2019-10-07	ercole-agent/ercole-agent-rhel6@1.5.13
-	2019-10-07	ercole-agent/ercole-agent-rhel6@1.6.0
-	2019-10-11	ercole-agent/ercole-agent-rhel6@1.6.1
-	2019-10-28	ercole-agent/ercole-agent-rhel6@1.6.2
-	2019-10-31	ercole-agent/ercole-agent-rhel6@1.6.3
-	2019-11-18	ercole-agent/ercole-agent-rhel6@1.6.4
-	2019-12-05	ercole-agent/ercole-agent-rhel6@1.6.5
-	2020-01-14	ercole-agent/ercole-agent-rhel6@1.6.6
-	2020-01-31	ercole-agent/ercole-agent-rhel6@1.6.7
-	2020-02-13	ercole-agent/ercole-agent-rhel6@1.6.8
-	2020-03-19	ercole-agent/ercole-agent-rhel6@1.6.9
-	2020-03-26	ercole-agent/ercole-agent-rhel6@1.6.10
-	2020-03-27	ercole-agent/ercole-agent-rhel6@1.6.11
-	2020-06-08	ercole-agent/ercole-agent-rhel6@1.6.12
-	2019-08-21	ercole-agent/ercole-agent-rhel7@1.5.0
-	2019-08-21	ercole-agent/ercole-agent-rhel7@1.5.1
-	2019-08-22	ercole-agent/ercole-agent-rhel7@1.5.2
-	2019-08-22	ercole-agent/ercole-agent-rhel7@1.5.3
-	2019-08-23	ercole-agent/ercole-agent-rhel7@1.5.4
-	2019-08-23	ercole-agent/ercole-agent-rhel7@1.5.5
-	2019-08-23	ercole-agent/ercole-agent-rhel7@1.5.6
-	2019-08-30	ercole-agent/ercole-agent-rhel7@1.5.7
-	2019-09-03	ercole-agent/ercole-agent-rhel7@1.5.8
-	2019-09-04	ercole-agent/ercole-agent-rhel7@1.5.10
-	2019-09-06	ercole-agent/ercole-agent-rhel7@1.5.11
-	2019-09-10	ercole-agent/ercole-agent-rhel7@1.5.12
-	2019-10-07	ercole-agent/ercole-agent-rhel7@1.5.13
-	2019-10-07	ercole-agent/ercole-agent-rhel7@1.6.0
-	2019-10-11	ercole-agent/ercole-agent-rhel7@1.6.1
-	2019-10-28	ercole-agent/ercole-agent-rhel7@1.6.2
-	2019-10-31	ercole-agent/ercole-agent-rhel7@1.6.3
-	2019-11-18	ercole-agent/ercole-agent-rhel7@1.6.4
-	2019-12-05	ercole-agent/ercole-agent-rhel7@1.6.5
-	2020-01-14	ercole-agent/ercole-agent-rhel7@1.6.6
-	2020-01-31	ercole-agent/ercole-agent-rhel7@1.6.7
-	2020-02-13	ercole-agent/ercole-agent-rhel7@1.6.8
-	2020-03-19	ercole-agent/ercole-agent-rhel7@1.6.9
-	2020-03-26	ercole-agent/ercole-agent-rhel7@1.6.10
-	2020-03-27	ercole-agent/ercole-agent-rhel7@1.6.11
-	2020-06-08	ercole-agent/ercole-agent-rhel7@1.6.12
-	2019-08-21	ercole-agent/ercole-agent-win@1.5.0
-	2019-08-21	ercole-agent/ercole-agent-win@1.5.1
-	2019-08-22	ercole-agent/ercole-agent-win@1.5.2
-	2019-08-22	ercole-agent/ercole-agent-win@1.5.3
-	2019-08-23	ercole-agent/ercole-agent-win@1.5.4
-	2019-08-23	ercole-agent/ercole-agent-win@1.5.5
-	2019-08-23	ercole-agent/ercole-agent-win@1.5.6
-	2019-08-30	ercole-agent/ercole-agent-win@1.5.7
-	2019-09-03	ercole-agent/ercole-agent-win@1.5.8
-	2019-09-04	ercole-agent/ercole-agent-win@1.5.10
-	2019-09-06	ercole-agent/ercole-agent-win@1.5.11
-	2019-09-10	ercole-agent/ercole-agent-win@1.5.12
-	2019-10-07	ercole-agent/ercole-agent-win@1.5.13
-	2019-10-07	ercole-agent/ercole-agent-win@1.6.0
i	2019-10-11	ercole-agent/ercole-agent-win@1.6.1
-	2019-10-28	ercole-agent/ercole-agent-win@1.6.2
-	2019-10-31	ercole-agent/ercole-agent-win@1.6.3
-	2019-11-18	ercole-agent/ercole-agent-win@1.6.4
-	2019-12-05	ercole-agent/ercole-agent-win@1.6.5
-	2020-01-14	ercole-agent/ercole-agent-win@1.6.6
-	2020-01-31	ercole-agent/ercole-agent-win@1.6.7
-	2020-02-13	ercole-agent/ercole-agent-win@1.6.8
-	2020-03-19	ercole-agent/ercole-agent-win@1.6.9
-	2020-03-26	ercole-agent/ercole-agent-win@1.6.10
-	2020-03-27	ercole-agent/ercole-agent-win@1.6.11
-	2020-06-08	ercole-agent/ercole-agent-win@1.6.12
amreo@amreo-ubuntu-pc:/tmp/ercole$ rm distributed_files/index.json
amreo@amreo-ubuntu-pc:/tmp/ercole$ ./ercole -c override2.toml repo list
amreo@amreo-ubuntu-pc:/tmp/ercole$
```

**Desktop (please complete the following information):**
 - OS: ubuntu 18.04.04 LTS
 - ercole version: 73ce3ab6984c11247d3d171fa2379e614c308f77  

**Additional context (optional)**
This problem affect repository.ercole.io https://repository.ercole.io/index.json and prevents ercole to use a ercole-reposervice server as upstream like https://repository.ercole.io

**Possible solution (optional)**
Add a internal repository that point to itself?

### PR DESCRIPTION
**Pull request by cirelli94**
Fix #320

### CODE REVIEW

File: cmd/repo.go [hunk 1]
```diff
@@ -283,9 +267,74 @@ func readOrUpdateIndex() repo.Index {
 		art.SetUninstaller(verbose, ercoleConfig.RepoService.DistributedFiles)
 	}
 
+	index = append(index, getArtifactsNotIndexed(index, ercoleConfig.RepoService.DistributedFiles)...)
```
Comment (amreo) [inline cmd/repo.go:270]: Maybe the name getArtifactsNotInUpstreamRepository or getArtifactsNotUpstramed is better than getArtifactsNotIndexed

File: cmd/repo.go [hunk 2]
```diff
@@ -283,9 +267,74 @@ func readOrUpdateIndex() repo.Index {
...
+	artifactsNotIndexed := make(repo.Index, 0)
+	for _, file := range filesNotIndexed {
+		artifactInfo := new(repo.ArtifactInfo)
+		artifactInfo.Filename = filepath.Base(file.Name())
+
+		if err := artifactInfo.SetInfoFromFileName(artifactInfo.Filename); err != nil {
+			continue
+		}
+
+		artifactInfo.Repository = "???"
```
Comment (amreo) [inline cmd/repo.go:290]: Maybe it's better to use a "local" as repository name

File: cmd/repo.go [hunk 3]
```diff
@@ -283,9 +267,74 @@ func readOrUpdateIndex() repo.Index {
...
+		artifactInfo.Installed = true
+		artifactInfo.ReleaseDate = file.ModTime().Format("2006-01-02")
+		artifactInfo.UpstreamType = "???"
```
Comment (amreo) [inline cmd/repo.go:293]: Maybe it's better to use "local" as upstream type

File: cmd/repo.go [hunk 4]
```diff
@@ -283,9 +267,74 @@ func readOrUpdateIndex() repo.Index {
...
+
+			fileInfo, err := os.Stat(filePath)
+			if err != nil || fileInfo.IsDir() {
+				return nil
+			}
+
+			filesNotIndexed = append(filesNotIndexed, fileInfo)
+
+			return nil
+		})
```
Comment (amreo) [inline cmd/repo.go:330]: You are indexing too much files! You need to index only artifacts in /all.

Comment (amreo) [reply cmd/repo.go:330]: Some files should not be indexed (e.g index.json, shared/*) and I suspect you have duplicates in the index

File: cmd/repo.go (hunk 1 above)
Comment (cirelli94) [reply cmd/repo.go:270]: But that's not true: that method check scan filesystem for installed artifacts not in passed index, it doesn't check upstream repo!

File: cmd/repo.go (hunk 4 above)
Comment (cirelli94) [reply cmd/repo.go:330]: Why index only the files in `/all`? If a file is inserted elsewhere isn't important?
This method do not insert this files in the index, in fact index.json etc aren't indexed.
This list is passed to getArtifactsNotIndexed that checks each file if is an artifact, so if they match against any {ercole-agent,ercole} regex.
There aren't files duplicated here, but there are duplicates from `/all` and specific folders yes, but they are both removed later.

**Comment by cirelli94** [comment]
> What happen if you create a directory upsteam, download a older version of ercole-agent, install it, remove it from the directory, download a newer version, `ercole repo install ercole-agent`?

`ercole repo install ercole-agent` doesn't work:
```
$ ./ercole -c override.toml repo install ercole-agent             
The argument "ercole-agent" wasn't undestood
```

> What happen if you try to install a file in local repository?

This PR shouldn't affect the way you install a file in local repository via `ercole repo install`.

> What happen if you try to remove a file from the local repository(e.g non in upstream)? And launch ercole repo list? It's included?

image


> What happen if you create a directory upsteam, download a older version of ercole-agent, install it, remove it from the directory, download a newer version, `ercole repo update`?

image


> What artifact are included in the output of `ercole repo list`?
It return the artifacts from the scan of repositories and the files in the local distributed_files directory that match any supported filename by regex in artifact.go/SetInfoFromFileName.
This is maybe a little bit hidden under the hood "feature".

So... Should I only check `/all` directory"? And return all and only files/artefacts in that directory?

File: cmd/repo.go (hunk 4 above)
Comment (amreo) [reply cmd/repo.go:330]: Because I may want to have multiple ercole-agent distribution, which the filename is the same but that the content may differ a little e.g. with different ercole-agent position...

**Comment by amreo** [comment]
Yes, you should check only /all directory

**Comment by amreo** [comment]
> ercole repo install ercole-agent doesn't work:
ercole repo list output?

**Comment by amreo** [comment]
> This PR shouldn't affect the way you install a file in local repository via ercole repo install.
So if you run `ercole repo install ercole-agent`, it should do anything?

**Comment by amreo** [comment]
> What happen if you try to remove a file from the local repository(e.g non in upstream)? And launch ercole repo list? It's included?
By remove I mean ercole repo remove local/ercole-agent...@1.6.12

**Comment by amreo** [comment]
> What happen if you create a directory upsteam, download a older version of ercole-agent, install it, remove it from the directory, download a newer version, ercole repo update?

In the output ercole-agent-rhel7@1.6.12 is indexed twice

**Comment by amreo** [comment]
> What happen if you create a directory upsteam, download a older version of ercole-agent, install it, remove it from the directory, download a newer version, ercole repo update?

Can you install createrepo and redo the experiment?

File: cmd/repo.go (hunk 4 above)
Comment (amreo) [reply cmd/repo.go:330]: Because other files should not be managed by ercole or because it's a link (or metadata) to /all.

Comment (amreo) [reply cmd/repo.go:330]: I don't want to rely on artifacts regexes...

Comment (cirelli94) [reply cmd/repo.go]: Okay, I update and:
I do not rely on regexes.
I check only `/all` folder.

**Comment by cirelli94** [comment]
> So if you run ercole repo install ercole-agent, it should do anything?

If you insert a correct local file name, so that it should do something, it effectively do anything because it's already installed.

> By remove I mean ercole repo remove local/ercole-agent...@1.6.12

It removes correctly the artifact now.
If it's recognized via a regex it removes it even from specific directory osFamily/os/arch.

> In the output ercole-agent-rhel7@1.6.12 is indexed twice
In the output ercole-agent-rhel7@1.6.12 is indexed twice

Yes because it founded it in a directory that wasn't `all`. There's no more.

>> What happen if you create a directory upsteam, download a older version of ercole-agent, install it, remove it from the directory, download a newer version, ercole repo update?

> Can you install createrepo and redo the experiment?

image
image

File: cmd/repo.go [hunk 5]
```diff
@@ -279,18 +282,23 @@ func getArtifactsNotIndexed(index repo.Index, distributedFiles string) repo.Inde
...
 	artifactsNotIndexed := make(repo.Index, 0)
+
 	for _, file := range filesNotIndexed {
 		artifactInfo := new(repo.ArtifactInfo)
 		artifactInfo.Filename = filepath.Base(file.Name())
 
 		if err := artifactInfo.SetInfoFromFileName(artifactInfo.Filename); err != nil {
-			continue
+			artifactInfo.Name = artifactInfo.Filename
+			artifactInfo.Version = "unknown"
```
Comment (amreo) [inline cmd/repo.go:292]: Are you sure that "unknown" don't broke any version checking???

File: cmd/repo.go [hunk 6]
```diff
@@ -279,18 +282,23 @@ func getArtifactsNotIndexed(index repo.Index, distributedFiles string) repo.Inde
...
+			artifactInfo.Arch = "unknown"
+			artifactInfo.OperatingSystemFamily = "unknown"
+			artifactInfo.OperatingSystem = "unknown"
```
Comment (amreo) [inline cmd/repo.go]: Why do you not want to skip artifacts when err != nil?

File: cmd/repo.go [hunk 7]
```diff
@@ -303,13 +311,12 @@ func getFilesNotIndexed(index repo.Index, distributedFiles string) []os.FileInfo
...
 	for _, artifact := range index {
 		if artifact.Installed {
-			installedInIndex[artifact.FilePath(distributedFiles)] = true
 			installedInIndex[filepath.Join(distributedFiles, "all", artifact.Filename)] = true
 		}
 	}
 
 	filesNotIndexed := make([]os.FileInfo, 0)
-	err := filepath.Walk(distributedFiles,
+	err := filepath.Walk(filepath.Join(distributedFiles, "all"),
```
Comment (amreo) [inline cmd/repo.go:319]: Why do you not use a simple filepath.Glob (https://golang.org/pkg/path/filepath/#Glob)?

File: cmd/repo.go (hunk 6 above)
Comment (cirelli94) [reply cmd/repo.go]: > I don't want to rely on artifacts regexes...

If you don't want to rely on artifacts regexes, I think we need to accept all files in `/all/` even if they don't comply to one regex.
If you have another solution, please, explain.

File: cmd/repo.go (hunk 5 above)
Comment (cirelli94) [reply cmd/repo.go:292]: What do you think could be a good version for this artifacts?

File: cmd/repo.go (hunk 7 above)
Comment (cirelli94) [reply cmd/repo.go:319]: Because filepath.Glob check only files inside `/all` without walk any directory inside it.
But if we don't want that there's any directory inside it, it work good.

Comment (cirelli94) [reply cmd/repo.go:319]: Because it doesn't walk inside directories, but if it is what we want it's okay.

File: cmd/repo.go (hunk 6 above)
Comment (amreo) [reply cmd/repo.go]: Accept all files /all/ that comply with regex?

I think it's a better idea to WARN if a foreign file/directory is found.

File: cmd/repo.go (hunk 7 above)
Comment (amreo) [reply cmd/repo.go:319]: I think it's a good idea

File: cmd/repo.go (hunk 6 above)
Comment (cirelli94) [reply cmd/repo.go]: Ok: let's accept the file but I'm going to add a WARN log!

File: cmd/repo.go (hunk 7 above)
Comment (cirelli94) [reply cmd/repo.go:319]: Ok, I'm going to add a WARN log for any directory I found, but I won't add files within!

**Comment by cirelli94** [comment]
@amreo it should be ok now, let me know if something is missing, or merge it otherwise!

File: cmd/repo.go [hunk 8]
```diff
@@ -191,29 +200,38 @@ func scanErcoleReposerviceRepository(upstreamRepo config.UpstreamRepository) (re
...
-		return scanDirectoryRepository(repo)
-	case "ercole-reposervice":
-		return scanErcoleReposerviceRepository(repo)
-	default:
-		return nil, fmt.Errorf("Unknown repository type %q of %q", repo.Type, repo.Name)
+func scanRepository(upstreamRepo config.UpstreamRepository) (repo.Index, error) {
+	if strings.TrimSpace(upstreamRepo.Name) == "local" {
+		return nil,
+			fmt.Errorf("\"local\" isn't a valid name for an upstream repository")
 	}
```
Comment (amreo) [inline cmd/repo.go:207]: Maybe move the check down within the switch?
```
	case repo.UpstreamTypeLocal:
		return nil,
			fmt.Errorf("\"local\" isn't a valid type for an upstream repository")
```

**Review by amreo — CHANGES_REQUESTED** [review]

File: cmd/repo.go (hunk 8 above)
Comment (cirelli94) [reply cmd/repo.go:207]: If you check it only for UpstreamTypeLocal, you could as well have "local" for a repo you defined and others "local" files for the true ones, added by this PR.
Instead, if you check for every repo, you assure you haven't two repo with the same "local" name, as far as silly this could be.

Comment (amreo) [reply cmd/repo.go:207]: Ok
