### PR TITLE
[BUG] Verify "Real Application Clusters One Node" number of licenses calculation

### LINKED ISSUE #661: [BUG] Verify "Real Application Clusters One Node" number of licenses calculation
**Describe the bug**
The number of "Real Application Clusters One Node" Licenses is wrongly calculated

**Expected behavior**
If a server has a Real Application Clusters license the related Real Application Clusters One Node doesn't have to be count

### PR DESCRIPTION
**Pull request by uortizrodas**
Fix #661

### CODE REVIEW

File: api-service/service/hosts.go [hunk 1]
```diff
@@ -254,7 +256,22 @@ func (as *APIService) GetHost(hostname string, olderThan time.Time, raw bool) (*
...
+						realApplicationClusters = true
+					}
+
+					if realApplicationClusters && lic.Name == "Real Application Clusters One Node" && lic.Count > 0 {
+						indexList = append(indexList, j)
+					}
+				}
+			}
+			if len(indexList) > 0 {
+				for _, i3 := range indexList {
```
Comment (cirelli94) [inline api-service/service/hosts.go:270]: Please, don't use i3!
If `i` has already been taken, you can go for `j`, `k`, `l`...

**Review by cirelli94 — CHANGES_REQUESTED** [review]
Please add some tests that cover this use case!

**Review by cirelli94 — CHANGES_REQUESTED** [review]
Add more tests :)
